# Generated by Django 5.2.8 on 2025-11-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='services.service')),
            ],
            options={
                'db_table': 'favorites',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='favorites_user_id_f73cef_idx')],
                'unique_together': {('user_id', 'service')},
            },
        ),
    ]
