# Generated by Django 5.2.8 on 2025-11-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('rating_sum', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('favorites_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('bookings_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.BigIntegerField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'db_table': 'service_images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider_id'], name='services_provide_54febe_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_published', 'is_active'], name='services_categor_665edb_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='services_created_6a9750_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-rating_avg'], name='services_rating__ac4b65_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceimage',
            index=models.Index(fields=['service', 'order'], name='service_ima_service_7189df_idx'),
        ),
    ]
