# Generated by Django 5.2.8 on 2025-11-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROVIDER', 'Provider'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_status', models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
