# Generated by Django 5.2.8 on 2025-11-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(db_index=True)),
                ('provider_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('negotiating', 'En Negociación'), ('accepted', 'Aceptado'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('canceled_by_customer', 'Cancelado por Cliente'), ('canceled_by_provider', 'Cancelado por Proveedor'), ('rejected', 'Rechazado')], default='pending', max_length=30)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('booking_notes', models.TextField(blank=True, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
            ],
            options={
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['customer_id', 'status'], name='bookings_custome_b789e2_idx'), models.Index(fields=['provider_id', 'status'], name='bookings_provide_f84a5e_idx'), models.Index(fields=['-created_at'], name='bookings_created_8ec366_idx')],
            },
        ),
    ]
