# Generated by Django 5.2.8 on 2025-11-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_id', models.BigIntegerField(db_index=True)),
                ('reported_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Contenido Inapropiado'), ('fraud', 'Fraude'), ('spam', 'Spam'), ('harassment', 'Acoso'), ('poor_service', 'Mal Servicio'), ('other', 'Otro')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_review', 'En Revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Desestimado')], default='open', max_length=20)),
                ('admin_user_id', models.BigIntegerField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_status_d7deb7_idx'), models.Index(fields=['reporter_id'], name='reports_reporte_5cbb43_idx'), models.Index(fields=['reported_user_id'], name='reports_reporte_225900_idx')],
            },
        ),
    ]
