# Generated by Django 5.2.8 on 2025-11-11 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.BigIntegerField(db_index=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(fields=['service', '-created_at'], name='reviews_service_e34807_idx'), models.Index(fields=['reviewer_id'], name='reviews_reviewe_965d53_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking')],
            },
        ),
    ]
