# Generated by Django 5.2.8 on 2025-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='devicetoken',
            name='device_toke_user_id_25a987_idx',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user_id'], name='device_toke_user_id_25a987_idx'),
        ),
    ]
