# Generated by Django 5.2.5 on 2025-11-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
