# Generated by Django 5.2.5 on 2025-11-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationparticipant_cleared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
