# Generated by Django 5.2.5 on 2025-11-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_service_price'),
        ('chat', '0003_conversationparticipant_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='service_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['service_id'], name='conversatio_service_541499_idx'),
        ),
    ]
