# Generated by Django 5.2.8 on 2025-12-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_service_id_alter_conversation_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
